// Generated by CoffeeScript 1.10.0

/*
 * Flatten an arbitrarily deep nested array
 *
 * @param {Array} arr
 * @return {Array}
 * @api public
 */

(function() {
  var flatten;

  flatten = function(arr, r) {
    var i, len;
    if (r === void 0 && !Array.isArray(arr)) {
      throw "an array input expected";
    }
    r = r || [];
    len = arr.length;
    i = -1;
    while (++i < len) {
      if (Array.isArray(arr[i])) {
        flatten(arr[i], r);
      } else {
        r.push(arr[i]);
      }
    }
    return r;
  };

  module.exports = flatten;

}).call(this);

//# sourceMappingURL=flatten.js.map
