// Generated by CoffeeScript 1.10.0
(function() {
  var flatten, test;

  test = require("nodeunit");

  flatten = require("./flatten.js");

  test.assert.throws((function() {
    return flatten(null);
  }));

  test.assert.deepEqual(flatten([]), []);

  test.assert.deepEqual(flatten([[[[]]]]), []);

  test.assert.deepEqual(flatten([1]), [1]);

  test.assert.deepEqual(flatten([1, 2]), [1, 2]);

  test.assert.deepEqual(flatten([[1, [2, [[3]]]], 4]), [1, 2, 3, 4]);

}).call(this);

//# sourceMappingURL=flatten_test.js.map
